apiVersion: v1
kind: Service
metadata:
  name: fifaapp-backend-svc
  namespace: fifaapp
spec:
  type: ClusterIP
  selector:
    app: fifaapp-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
