apiVersion: v1
kind: Service
metadata:
  name: fifaapp-frontend-svc
  namespace: fifaapp
spec:
  type: ClusterIP
  selector:
    app: fifaapp-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
